on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22, 24 ]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run bundle
      - name: Setup K6
        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@c6b79182b9b666aa4f630f4a6be9158ead62536e # v1
        with:
          path: dist/get-200-status-test.js
