on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22, 24 ]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run bundle
      - name: Setup K6
        uses: grafana/setup-k6-action@43b9fc21641a76002687994433dd586f56e791b1 # v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@4082a08c7e40cf6d65863911077dfb60ae0a4f04 # v1
        with:
          path: dist/get-200-status-test.js
